### ISSUE TITLE
Pyanodon - recipes missing

### ISSUE THREAD

**Issue by DRouve** [ShadowTheAge/yafc#104]
Hello! Thanks for this awesome tool!
YAFC won't show some recipes from PYAlienLife. For example he can't see that Fawogae production recipes changed and now requires Fawogae spores, but YAFC doesn't even show this item and Spore Collector building which produces it.

![yafc](https://user-images.githubusercontent.com/59864935/112978083-8be6a000-915f-11eb-9176-b8eeae3af489.png)
![faw](https://user-images.githubusercontent.com/59864935/112978087-8c7f3680-915f-11eb-83a3-39c82bb3368f.png)

**Comment by ShadowTheAge** [comment]
Hi, can you please attach a new game save file for syncing mods?
Because Py was definitely working, including PyAL and spores

**Comment by DRouve** [comment]
Just fixed everything by exiting YAFC and Factorio, then opening YAFC. All recipes including PyAL and spores are in calculator. Seems to me that Factorio somehow blocked access to mod files, that's why YAFC won't show recipes.
Guess you should add this to FAQ or something :D
Thanks and sorry for trouble!

**Comment by ShadowTheAge** [comment]
The reason is that Factorio only makes changes to files after exiting. That includes mod-list and mod-settings. So, yes, YAFC only supports loading modpacks that were loaded in Factorio before.

I show that info when there is an error with mod configuration during loading, but it happens so that your setup loaded without mod config errors.
