### ISSUE TITLE
[Feature request] Some suggestions

### ISSUE THREAD

**Issue by Septiple** [ShadowTheAge/yafc#115]
Let me start by saying that I'm super happy I found this program, I love it for my Pyanodon's run. I was running into Helmod and Factory Planner bugs and limitations, and this program is much more powerful and usable. So thank you for making this!

Two small suggestions, and one larger one:
1) add an option to hide all recipes that are locked behind milestones, for those who want to play without getting later recipes spoiled for them.

2) I think the list of recipes in the 'add production recipe' popup are sorted by their YAFC cost, so the cheapest one is at the top. It also displays the 'current' YAFC cost, which I assume is the cost with only unlocked recipes. It would be cool if we can have an option to sort by this 'current' cost, and also if the option under my suggestion 1) hides the 'final' YAFC cost.

3) I was trying to make a table that created syngas using only raw coal using only red science recipes. At this point, you have 2 recipes to go from raw coal to coal and 2 to go from coal to coke, 1 that is more efficient and 1 that generates tar and coal gas. It's therefore not obvious how to balance these recipes to get the target syngas production.

I was trying to optimise for minimal raw coal use, but I'm not sure what target function YAFC uses to optimize the recipe. I was able to end up with a lower raw coal use by disabling some recipes, so I think it's total power consumption maybe? In any case, it would be neat if we had several target quantities to optimize and could choose between then, like minimize a certain resource cost, or minimize power, or pollution. Maybe even a linear function in the resources and power?

**Comment by ShadowTheAge** [comment]
1. Well, getting spoiled is kind of the point of YAFC. I think it would be too hard to hide everything everywhere and also hide everything from now on. You can also get "spoiled" just by looking at the Factorio in-game tech tree.

2. They are sorted by (output production count / yafc cost of the recipe). Sorting by current yafc cost is possible, but current yafc cost is not accurate especially at early milestones, I am a little afraid of breaking something in edge cases. Primary "yafc cost" is an heuristic that yafc uses internally, the "current yafc cost" is currently only a display thing and if that fails to calculate - that doesn't matter much. I may try that. (I am also not a fan of adding options for everything that is not immediately obvious for users - yafc is already kind of complicated especially for someone that just started using it)

3. That is a long staying "todo" - add an option for aggressive minimization/maximization of a link. I see it useful but it is also not trivial because there may be only one optimization criteria.

**Comment by Septiple** [comment]
Thanks for the speedy and extensive reply! Your comments regarding 1 and 2 are fair. I was hoping they'd be easy things to implement, but you give good reasons not to do them.

Regarding 3: that is not trivial indeed. I think you end up having to implement full-blown [linear programming](https://en.wikipedia.org/wiki/Linear_programming) to allow for optimizing targets like that. On the plus side, if you do implement or re-use a linear programming solver, that might end up simplifying the rest of your code, as linear programs are so expressive.

**Comment by Septiple** [comment]
Ah, nice, thanks!
