### ISSUE TITLE
[BUG] JSON parser fails on ill-formed JSON files

### ISSUE THREAD

**Issue by l0rem1psum** [ShadowTheAge/yafc#122]
**YAFC Version**: YAFC beta v0.5.7.1

**Description**: In some mods, the `info.json` files are ill-formed and it can cause YAFC to fail. A typical JSON file starts with `0x7B` (i.e. `'{'`). However, in ill-formed JSON, it may start with other characters (e.g. `0xEF`). This causes YAFC to crash with the following stack trace (which hopefully can be more complete so users can identify problems on their own).
![image](https://user-images.githubusercontent.com/28675546/121542941-1f2f3200-ca3b-11eb-9959-fcb4cd4164c3.png)

**Comment by ShadowTheAge** [comment]
I need that ill-formed json file. Also the stack trace is incomplete

**Comment by l0rem1psum** [comment]
Yes, that's what I suppose too.

The mod is not an official mod, so it's not on Factorio mod portal. But I have uploaded it [here](https://drive.google.com/file/d/1URj8lb_rNYOaqR3k7e_po3lM8-NjoSK-/view?usp=sharing).

**Comment by ShadowTheAge** [comment]
Sorry for not answering earlier, I have already implemented a fix before and checked now that the fix is working correctly
This will be fixed in the next release, if you want it now you can build it https://github.com/ShadowTheAge/yafc/blob/master/Docs/HowToBuild.md

Another issue is the mod doesn't have English locale (that is used by default and as a fallback) and yafc doesn't have font included that has Chinese glyphs. Unfortunately I don't have acceptable fix for now that is not a workaround.

**Comment by ShadowTheAge** [comment]
v0.5.8 with the fix has been published here https://github.com/ShadowTheAge/yafc/releases
Feel free to reopen the issue if needed
