### ISSUE TITLE
Suggestion:  Allow setting and viewing # of belts, rather than items per second

### ISSUE THREAD

**Issue by binarycow** [ShadowTheAge/yafc#14]

**Comment by ShadowTheAge** [comment]
Do you mean under the item?
Because I have thought about it as an additional column, but it doesn't work like this because recipes can have multiple inputs and outputs. I didn't think about replacing the number under the item

I am thinking about introducting "units of measure" that, for example, will allow to specify amounts per minute/hour and not only per second. This belt idea works with these "units of measure" very nicely

**Comment by binarycow** [comment]
For example, in Factory Planner, I can choose the unit of time (seconds, minutes, hours) that all of my numbers represent.  So, I can enter "45" and select "per second", and it means that everything is calculated to produce 45 per second.  If I enter "45" and select "per minute", it means that everything is calculated to produce 45 per minute.  (The numbers I'm entering here are the amount of **end product** I want.

Then, there's another option, to view the inputs/outputs in items/[unit of time], belts, or items/second/machine.  So, if I select my target recipe as iron gear, 45 per minute... it says I need 45 iron gear per minute, and 90 iron plate per minute.  

If I select that I want 900 green circuits per minute (to fill a yellow belt), and select to display in "belts", I can see that I need 3 yellow belts of copper wire.  In the preferences, I can change my desired belt.  The belts that I can select from are pulled from my mods... So, it accurately accounts for the extra belts in bob's mods, for instance.

**Comment by ShadowTheAge** [comment]
"Units of measure", be that minutes, "45-second-intervals" or belts are definitely going to happen, but not the next release

**Comment by ShadowTheAge** [comment]
Units of measure will be added in 0.4.3
