### ISSUE TITLE
[BUG] bad argument #1 to module

### ISSUE THREAD

**Issue by Shinhan** [ShadowTheAge/yafc#40]
YAFC 0.4.5
Factorio 0.18.22
All the mods are disabled atm (I can attach the mod-list.json if disabled mods could be the problem)
Windows 8.1

Anyway, the error pops up when first creating the new project. I picked the game directory and just clicked create new project. Also tried it with selecting a mod folder but same error.

Full error message:

~~~
(Core, lualib/util.lua):2: bad argument #1 to 'module' (string expected, got nil)
stack tracebak:
[C]: in ?
[C]: in function 'module'
(core, lualib/util.lua):2: in main chunk
[C]: in function 'require'
(base, data.lua):1: in main chunk
~~~

**Comment by ShadowTheAge** [comment]
I have checked with vanilla 0.18.22 and there are no problems, so disabled mods are the problem.
I think that some mods are not actually disabled, but they are not loaded because of missing dependency, and YAFC may do dependency checks slightly differently

So I will need all the mods, and I don't think that just mod-list.json will be enough (because this is probably related to mod versions, and mod-list.json doesn't contain versions)

**Comment by Shinhan** [comment]
Ah, that was a wrong Factorio game folder. Probably some old version. When I used Steams "Browse local files" option it opened a different folder and YAFC worked on that folder correctly.
