### ISSUE TITLE
[Feature Request] Set beacon count per recipe and not globally for the complete production sheet

### ISSUE THREAD

**Issue by SuperTux88** [ShadowTheAge/yafc#48]
It took me a while to find where to set beacons, because I expected that it can also be set per line as the modules. In Seablock/Angel/Bob are a lot of different buildings with different sizes, and there is no way they all have the same numbers if beacons, so it would be great if I can adjust the number of beacons per line, and not only for the complete sheet.

**Comment by ShadowTheAge** [comment]
This is one of the features that is not very hard to do but that may become a problem for future features.
I think the next thing I am going to do is to allow to override module settings on a subtable basis.
I don't (currently) want to add beacon settings on a per-recipe basis, but I can add dependency on a building size.

**Comment by andreasferber** [comment]
Not being able to set it on a per recipe instance basis unfortunately makes the tool (or at least the calculation of assembler counts) pretty much useles for example with Krastorio 2. And being able to set it on a building size basis wouldn't help with that.

K2 adds some late game production buildings where the power consumption can go into the hundreds of megawatts for a single building when you module them. They have a very high production rate, so you generally don't need to fully speed beacon them even when feeding other things that _are_ fully speed beaconed themselves.

Unlike vanilla, this makes efficiency modules actually useful, or basically even required if you don't want to overbuild your power production by an order of magnitude so that you don't get intermittent massive brownouts when a number of those production buildings all happen to kick in simultaneously. However it requires carefully balancing speed vs. efficiency modules for every production line so that you get the desired throughput for a minimum peak power consumption.

Helmod for example also struggles with this, even though it is much more flexible with regards to beacons, as it doesn't let you put in that you want let's say 5 beacons with speed and 4 beacons with efficiency modules on a building, but at least you can use it to find out how many speed beacons you need to meet the production target. You can then fill in efficiency beacons as you build it.

And even in vanilla, there's plenty of reasons why you'd want let's say fully 12 beaconed science pack assemblers while using only 8 beacons for the smelters, or 10 beacons for green circuits because it lets you use direct insertion.

**Comment by ShadowTheAge** [comment]
The ability to set beacon numbers wouldn't help here too, setting up "5 speed + 4 efficiency" would require having a full-size beacon/moduile editor for each recipe, and that's what I don't want to do. I understand the use-case, nut I am looking for a better solution.

That's a problem with modfules. Adding some additional options would solve some use-cases but still not all.
A very simplistic but working solution would be to allow inputting raw productivity/efficiency/speed numbers. Thats not very convinient, but at least solves all module/beacon combinations.

**Comment by ShadowTheAge** [comment]
I will add something in 0.4.9

**Comment by SuperTux88** [comment]
Yes, works as expected now :+1:

**Comment by ShadowTheAge** [comment]
v0.4.9 have been released containing this feature

**Comment by SuperTux88** [comment]
Found a little "bug", when overriding modules, you show the current effects. But it doesn't include the default-beacons from the production sheet, if the beacons aren't overridden.

**Comment by ShadowTheAge** [comment]
I'll fix it but I won't make a new release because of it :)

**Comment by SuperTux88** [comment]
Yeah, sure, it's only a minor thing :) It's still use the correct speed effects for the number of buildings needed.

**Comment by ShadowTheAge** [comment]
v0.4.10 have been published with a fix

**Comment by SuperTux88** [comment]
Thanks. I think this now solves all my use-cases, so I think you can close this, unless you still planned to add something else.

**Comment by ShadowTheAge** [comment]
well I am now developing YAFC mostly to solve my own problems. If I want some feature, I'll add it even if it is a niche one :)
I have 0.5.x plans but I now use my free time to play Factorio and not developing YAFC :)
