### ISSUE TITLE
[BUG] PY mods

### ISSUE THREAD

**Issue by immortal-sniper1** [ShadowTheAge/yafc#52]
last version 

for some reason adding some plants makes the tab unsolvable 

also a lot of tuulpa recipes are broken they display 0 soil tho that is not true

**Comment by ShadowTheAge** [comment]
Please when creating a bug, provide some information. "some plants" is not an information.

**Comment by immortal-sniper1** [comment]
rennea & tuulpa , they are the only ones i found it

**Comment by immortal-sniper1** [comment]
also apparently phytoplankton building mk2-4 are not there for a reason

**Comment by immortal-sniper1** [comment]
the building is but the icon is not to be more precise

**Comment by ShadowTheAge** [comment]
I still need more info. Py mods have about 100 objects that have "rennea" in its name. I need your project file at minimum (and probably all the mods, but if you create a new project with just this error and nothing else, it may be enough)

![image](https://user-images.githubusercontent.com/7020122/84059814-dece4b80-a9c3-11ea-8062-1ee926275747.png)

**Comment by ShadowTheAge** [comment]
Also phytoplankton building icons are also there at least in my Py version.
![image](https://user-images.githubusercontent.com/7020122/84059964-1ccb6f80-a9c4-11ea-9af4-2689cd3e230f.png)

**Comment by immortal-sniper1** [comment]
it is plancton building ice on when it is in a tab that uses plancton as a ingredient
also with water+flue gas recipe to be more precise

**Comment by immortal-sniper1** [comment]
```I still need more info. Py mods have about 100 objects that have "rennea" in its name. I need your project file at minimum (and probably all the mods, but if you create a new project with just this error and nothing else, it may be enough)```
rennea as a plant mk1 (the one you use in most of the actual recipes)

**Comment by immortal-sniper1** [comment]
[project3.yafc.txt](https://github.com/ShadowTheAge/yafc/files/4751106/project3.yafc.txt)

**Comment by immortal-sniper1** [comment]
as for mods all py mods on last version

**Comment by ShadowTheAge** [comment]
I don't see any problems with the model
You want to extract co2 from organics but you can't consume all the organcics you are getting because you cant spend all these co2.

You need to allow overproduction to organics (or some other product that you want to get more of) OR remove organics link at all.

The warning you are getting tells you exactly what are you need to do
![image](https://user-images.githubusercontent.com/7020122/84188558-7737ff00-aa9c-11ea-8883-c2f95c014a16.png)
![image](https://user-images.githubusercontent.com/7020122/84188581-8454ee00-aa9c-11ea-9bb2-4df277ee4587.png)

Without the "allow overproduction" check box yafc tries to exactly match production with consumption exactly
